<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Test Report</title>
    <link href="assets/style.css" rel="stylesheet" type="text/css"/></head>
  <body onLoad="init()">
    <script>/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */


function toArray(iter) {
    if (iter === null) {
        return null;
    }
    return Array.prototype.slice.call(iter);
}

function find(selector, elem) { // eslint-disable-line no-redeclare
    if (!elem) {
        elem = document;
    }
    return elem.querySelector(selector);
}

function findAll(selector, elem) {
    if (!elem) {
        elem = document;
    }
    return toArray(elem.querySelectorAll(selector));
}

function sortColumn(elem) {
    toggleSortStates(elem);
    const colIndex = toArray(elem.parentNode.childNodes).indexOf(elem);
    let key;
    if (elem.classList.contains('result')) {
        key = keyResult;
    } else if (elem.classList.contains('links')) {
        key = keyLink;
    } else {
        key = keyAlpha;
    }
    sortTable(elem, key(colIndex));
}

function showAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(showExtras);
}

function hideAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(hideExtras);
}

function showExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.remove('collapsed');
    expandcollapse.classList.remove('expander');
    expandcollapse.classList.add('collapser');
}

function hideExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.add('collapsed');
    expandcollapse.classList.remove('collapser');
    expandcollapse.classList.add('expander');
}

function showFilters() {
    const filterItems = document.getElementsByClassName('filter');
    for (let i = 0; i < filterItems.length; i++)
        filterItems[i].hidden = false;
}

function addCollapse() {
    // Add links for show/hide all
    const resulttable = find('table#results-table');
    const showhideall = document.createElement('p');
    showhideall.innerHTML = '<a href="javascript:showAllExtras()">Show all details</a> / ' +
                            '<a href="javascript:hideAllExtras()">Hide all details</a>';
    resulttable.parentElement.insertBefore(showhideall, resulttable);

    // Add show/hide link to each result
    findAll('.col-result').forEach(function(elem) {
        const collapsed = getQueryParameter('collapsed') || 'Passed';
        const extras = elem.parentNode.nextElementSibling;
        const expandcollapse = document.createElement('span');
        if (extras.classList.contains('collapsed')) {
            expandcollapse.classList.add('expander');
        } else if (collapsed.includes(elem.innerHTML)) {
            extras.classList.add('collapsed');
            expandcollapse.classList.add('expander');
        } else {
            expandcollapse.classList.add('collapser');
        }
        elem.appendChild(expandcollapse);

        elem.addEventListener('click', function(event) {
            if (event.currentTarget.parentNode.nextElementSibling.classList.contains('collapsed')) {
                showExtras(event.currentTarget);
            } else {
                hideExtras(event.currentTarget);
            }
        });
    });
}

function getQueryParameter(name) {
    const match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
    return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
}

function init () { // eslint-disable-line no-unused-vars
    resetSortHeaders();

    addCollapse();

    showFilters();

    sortColumn(find('.initial-sort'));

    findAll('.sortable').forEach(function(elem) {
        elem.addEventListener('click',
            function() {
                sortColumn(elem);
            }, false);
    });
}

function sortTable(clicked, keyFunc) {
    const rows = findAll('.results-table-row');
    const reversed = !clicked.classList.contains('asc');
    const sortedRows = sort(rows, keyFunc, reversed);
    /* Whole table is removed here because browsers acts much slower
     * when appending existing elements.
     */
    const thead = document.getElementById('results-table-head');
    document.getElementById('results-table').remove();
    const parent = document.createElement('table');
    parent.id = 'results-table';
    parent.appendChild(thead);
    sortedRows.forEach(function(elem) {
        parent.appendChild(elem);
    });
    document.getElementsByTagName('BODY')[0].appendChild(parent);
}

function sort(items, keyFunc, reversed) {
    const sortArray = items.map(function(item, i) {
        return [keyFunc(item), i];
    });

    sortArray.sort(function(a, b) {
        const keyA = a[0];
        const keyB = b[0];

        if (keyA == keyB) return 0;

        if (reversed) {
            return keyA < keyB ? 1 : -1;
        } else {
            return keyA > keyB ? 1 : -1;
        }
    });

    return sortArray.map(function(item) {
        const index = item[1];
        return items[index];
    });
}

function keyAlpha(colIndex) {
    return function(elem) {
        return elem.childNodes[1].childNodes[colIndex].firstChild.data.toLowerCase();
    };
}

function keyLink(colIndex) {
    return function(elem) {
        const dataCell = elem.childNodes[1].childNodes[colIndex].firstChild;
        return dataCell == null ? '' : dataCell.innerText.toLowerCase();
    };
}

function keyResult(colIndex) {
    return function(elem) {
        const strings = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed',
            'Skipped', 'Passed'];
        return strings.indexOf(elem.childNodes[1].childNodes[colIndex].firstChild.data);
    };
}

function resetSortHeaders() {
    findAll('.sort-icon').forEach(function(elem) {
        elem.parentNode.removeChild(elem);
    });
    findAll('.sortable').forEach(function(elem) {
        const icon = document.createElement('div');
        icon.className = 'sort-icon';
        icon.textContent = 'vvv';
        elem.insertBefore(icon, elem.firstChild);
        elem.classList.remove('desc', 'active');
        elem.classList.add('asc', 'inactive');
    });
}

function toggleSortStates(elem) {
    //if active, toggle between asc and desc
    if (elem.classList.contains('active')) {
        elem.classList.toggle('asc');
        elem.classList.toggle('desc');
    }

    //if inactive, reset all other functions and add ascending active
    if (elem.classList.contains('inactive')) {
        resetSortHeaders();
        elem.classList.remove('inactive');
        elem.classList.add('active');
    }
}

function isAllRowsHidden(value) {
    return value.hidden == false;
}

function filterTable(elem) { // eslint-disable-line no-unused-vars
    const outcomeAtt = 'data-test-result';
    const outcome = elem.getAttribute(outcomeAtt);
    const classOutcome = outcome + ' results-table-row';
    const outcomeRows = document.getElementsByClassName(classOutcome);

    for(let i = 0; i < outcomeRows.length; i++){
        outcomeRows[i].hidden = !elem.checked;
    }

    const rows = findAll('.results-table-row').filter(isAllRowsHidden);
    const allRowsHidden = rows.length == 0 ? true : false;
    const notFoundMessage = document.getElementById('not-found-message');
    notFoundMessage.hidden = !allRowsHidden;
}
</script>
    <h1>report.html</h1>
    <p>Report generated on 27-Nov-2021 at 23:22:57 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a> v3.1.1</p>
    <h2>Environment</h2>
    <table id="environment">
      <tr>
        <td>Packages</td>
        <td>{"pluggy": "1.0.0", "py": "1.11.0", "pytest": "6.2.5"}</td></tr>
      <tr>
        <td>Platform</td>
        <td>Windows-10-10.0.22000-SP0</td></tr>
      <tr>
        <td>Plugins</td>
        <td>{"html": "3.1.1", "metadata": "1.11.0"}</td></tr>
      <tr>
        <td>Python</td>
        <td>3.10.0</td></tr></table>
    <h2>Summary</h2>
    <p>14 tests ran in 7.79 seconds. </p>
    <p class="filter" hidden="true">(Un)check the boxes to filter the results.</p><input checked="true" class="filter" data-test-result="passed" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="passed">5 passed</span>, <input checked="true" class="filter" data-test-result="skipped" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="skipped">0 skipped</span>, <input checked="true" class="filter" data-test-result="failed" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="failed">9 failed</span>, <input checked="true" class="filter" data-test-result="error" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="error">31 errors</span>, <input checked="true" class="filter" data-test-result="xfailed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xfailed">0 expected failures</span>, <input checked="true" class="filter" data-test-result="xpassed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xpassed">0 unexpected passes</span>
    <h2>Results</h2>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable result initial-sort" col="result">Result</th>
          <th class="sortable" col="name">Test</th>
          <th class="sortable" col="duration">Duration</th>
          <th class="sortable links" col="links">Links</th></tr>
        <tr hidden="true" id="not-found-message">
          <th colspan="4">No results found. Try to check the filters</th></tr></thead>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testNoReports::teardown</td>
          <td class="col-duration">0.02</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def empty_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:21: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testNoReportsForPothole::teardown</td>
          <td class="col-duration">0.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def empty_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:21: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testNoIndividualReportForPothole::teardown</td>
          <td class="col-duration">0.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def empty_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:21: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testNoVotesForPothole::teardown</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def empty_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:21: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testNoIndividualPothole::teardown</td>
          <td class="col-duration">0.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def empty_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:21: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testNoReportImages::teardown</td>
          <td class="col-duration">0.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def empty_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:21: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testNoIndividualReportImage::teardown</td>
          <td class="col-duration">0.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def empty_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:21: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testGetExistingPothole::teardown</td>
          <td class="col-duration">1.66</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/> -----------------------------Captured stdout setup------------------------------ <br/>https://www.howtogeek.com/wp-content/uploads/2018/08/Header.png
https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg
https://images.unsplash.com/photo-1541963463532-d68292c34b19?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mnx8fGVufDB8fHx8&amp;w=1000&amp;q=80
<br/> ------------------------------Captured stdout call------------------------------ <br/>b&#x27;{&quot;potholeID&quot;: 1, &quot;longitude&quot;: -61.277001, &quot;latitude&quot;: 10.726551, &quot;numReports&quot;: 2, &quot;expiryDate&quot;: &quot;2021-12-27&quot;}&#x27;
<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testGetExistingReport::teardown</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testGetNonExistentReport::teardown</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testGetAllReportsForPothole::teardown</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testGetAllReportImagesForPothole::teardown</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testGetIndividualReportImage::teardown</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testGetNonExistentIndividualReportImage::teardown</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testRegister::teardown</td>
          <td class="col-duration">0.02</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def empty_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:21: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testAddNewPotholeReportDriver::teardown</td>
          <td class="col-duration">0.12</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def users_in_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createTestUsers()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:31: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testMultipleReportsSamePothole::teardown</td>
          <td class="col-duration">0.14</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def users_in_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createTestUsers()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:31: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testDeleteExistingPotholeImageNotOwner::teardown</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testDeleteNonExistentPotholeImage::teardown</td>
          <td class="col-duration">0.03</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testAddPotholeImageNotOwner::teardown</td>
          <td class="col-duration">0.03</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/> ------------------------------Captured stdout call------------------------------ <br/>{&#x27;error&#x27;: &#x27;You are not the creator of this report!&#x27;}
<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testAddPotholeImage::teardown</td>
          <td class="col-duration">0.47</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/> ------------------------------Captured stdout call------------------------------ <br/>Pothole image succesfully added!
<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testAddPotholeImageInvalidImageURL::teardown</td>
          <td class="col-duration">0.83</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testUpdatePotholeDescriptionAsOwner::teardown</td>
          <td class="col-duration">0.05</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/> ------------------------------Captured stdout call------------------------------ <br/>{&quot;reportID&quot;: 1, &quot;userID&quot;: 1, &quot;potholeID&quot;: 1, &quot;dateReported&quot;: &quot;2021-11-28&quot;, &quot;description&quot;: &quot;Wide pothole!&quot;, &quot;votes&quot;: [], &quot;reportedImages&quot;: [{&quot;imageID&quot;: 4, &quot;reportID&quot;: 1, &quot;imageURL&quot;: &quot;https://media.gettyimages.com/photos/balanced-stones-on-a-pebble-beach-during-sunset-picture-id157373207?s=612x612&quot;}], &quot;reportedBy&quot;: &quot;Moses Darren&quot;}
<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testUpdatePotholeDescriptionAsNonOwner::teardown</td>
          <td class="col-duration">0.03</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testUpdatePotholeDescriptionNonExistent::teardown</td>
          <td class="col-duration">0.03</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testDeleteIndividualReportAsOwner::teardown</td>
          <td class="col-duration">0.05</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testDeleteIndividualReportNonExistent::teardown</td>
          <td class="col-duration">0.03</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testDeleteReportAfterNegativeVoteThreshold::teardown</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testUnVoteOnPothole::teardown</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testLoginValid::teardown</td>
          <td class="col-duration">0.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def users_in_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createTestUsers()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:31: PermissionError<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">App/tests/test_application.py::testLoginInvalidData::teardown</td>
          <td class="col-duration">0.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">@pytest.fixture<br/>    def users_in_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createTestUsers()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:31: PermissionError<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">App/tests/test_application.py::testNoPotholes</td>
          <td class="col-duration">0.03</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">empty_db = &lt;FlaskClient &lt;Flask &#x27;App.main&#x27;&gt;&gt;<br/><br/>    def testNoPotholes(empty_db):<br/>        response = empty_db.get(&#x27;/api/potholes&#x27;)<br/>&gt;       assert b&#x27;[]&#x27; in response.data and response.status_code == 200<br/><span class="error">E       assert (b&#x27;[]&#x27; in b&#x27;[{&quot;potholeID&quot;: 1, &quot;longitude&quot;: -61.454274, &quot;latitude&quot;: 10.432359, &quot;numReports&quot;: 1, &quot;expiryDate&quot;: &quot;2021-12-27&quot;}, {&quot;po...2-27&quot;}, {&quot;potholeID&quot;: 6, &quot;longitude&quot;: -61.466627, &quot;latitude&quot;: 10.648361, &quot;numReports&quot;: 1, &quot;expiryDate&quot;: &quot;2021-12-27&quot;}]&#x27;)</span><br/><span class="error">E        +  where b&#x27;[{&quot;potholeID&quot;: 1, &quot;longitude&quot;: -61.454274, &quot;latitude&quot;: 10.432359, &quot;numReports&quot;: 1, &quot;expiryDate&quot;: &quot;2021-12-27&quot;}, {&quot;po...2-27&quot;}, {&quot;potholeID&quot;: 6, &quot;longitude&quot;: -61.466627, &quot;latitude&quot;: 10.648361, &quot;numReports&quot;: 1, &quot;expiryDate&quot;: &quot;2021-12-27&quot;}]&#x27; = &lt;WrapperTestResponse 665 bytes [200 OK]&gt;.data</span><br/><br/>App\tests\test_application.py:47: AssertionError@pytest.fixture<br/>    def empty_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:21: PermissionError<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">App/tests/test_application.py::testGetNonExistentPothole</td>
          <td class="col-duration">0.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">empty_db = &lt;FlaskClient &lt;Flask &#x27;App.main&#x27;&gt;&gt;<br/><br/>    def testGetNonExistentPothole(empty_db):<br/>        response = empty_db.get(&quot;/api/potholes/3&quot;)<br/>&gt;       assert b&quot;No pothole data for that ID.&quot; in response.data and response.status_code == 404<br/><span class="error">E       assert (b&#x27;No pothole data for that ID.&#x27; in b&#x27;{&quot;potholeID&quot;: 3, &quot;longitude&quot;: -61.400837, &quot;latitude&quot;: 10.50223, &quot;numReports&quot;: 1, &quot;expiryDate&quot;: &quot;2021-12-27&quot;}&#x27;)</span><br/><span class="error">E        +  where b&#x27;{&quot;potholeID&quot;: 3, &quot;longitude&quot;: -61.400837, &quot;latitude&quot;: 10.50223, &quot;numReports&quot;: 1, &quot;expiryDate&quot;: &quot;2021-12-27&quot;}&#x27; = &lt;WrapperTestResponse 108 bytes [200 OK]&gt;.data</span><br/><br/>App\tests\test_application.py:100: AssertionError@pytest.fixture<br/>    def empty_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:21: PermissionError<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">App/tests/test_application.py::testAddNewPotholeReportStandard</td>
          <td class="col-duration">0.02</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">users_in_db = &lt;FlaskClient &lt;Flask &#x27;App.main&#x27;&gt;&gt;<br/><br/>    def testAddNewPotholeReportStandard(users_in_db):<br/>        reportDetails = {<br/>            &quot;longitude&quot; : -61.277001,<br/>            &quot;latitude&quot; : 10.726551,<br/>            &quot;constituencyID&quot; : &quot;arima&quot;,<br/>            &quot;description&quot;: &quot;Very large pothole spanning both lanes of the road.&quot;,<br/>            &quot;images&quot; : [<br/>                &quot;https://www.howtogeek.com/wp-content/uploads/2018/08/Header.png&quot;<br/>            ]<br/>        }<br/>    <br/>        user1 = getOneRegisteredUser(&quot;tester1@yahoo.com&quot;)<br/>        r = reportPotholeStandard(user1, reportDetails)<br/>    <br/>    <br/>        allReportsByUser = getAllPotholeReportsByUser(user1)<br/>        check2 = False<br/>    <br/>        for oneReportByUser in allReportsByUser:<br/>            if reportDetails[&quot;description&quot;] == oneReportByUser[&quot;description&quot;] and reportDetails[&quot;images&quot;][0] == oneReportByUser[&quot;reportedImages&quot;][0][&quot;imageURL&quot;]:<br/>                check2 = True<br/>    <br/>        rPotholes = getAllPotholes()<br/>        check1 = False<br/>        for pothole in rPotholes:<br/>            if reportDetails[&quot;longitude&quot;] == pothole[&quot;longitude&quot;] and reportDetails[&quot;latitude&quot;] == pothole[&quot;latitude&quot;]:<br/>                check1 = True<br/>    <br/>&gt;       assert check1 and check2 and &quot;Successfully added pothole report to database!&quot; in r[0][&quot;message&quot;] and r[1] == 201<br/><span class="error">E       assert (True and False)</span><br/><br/>App\tests\test_application.py:215: AssertionError@pytest.fixture<br/>    def users_in_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createTestUsers()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:31: PermissionError<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">App/tests/test_application.py::testDeleteExistingPotholeImage</td>
          <td class="col-duration">1.39</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">simulated_db = &lt;FlaskClient &lt;Flask &#x27;App.main&#x27;&gt;&gt;<br/><br/>    def testDeleteExistingPotholeImage(simulated_db):<br/>        user1 = getOneRegisteredUser(&quot;tester1@yahoo.com&quot;)<br/>    <br/>        potholeID = 1<br/>        reportID = 1<br/>        imageID = 1<br/>    <br/>        reportedImageBefore = getIndividualReportedImage(potholeID, reportID, imageID)<br/>    <br/>        res = deletePotholeReportImage(user1, potholeID, reportID, imageID)<br/>    <br/>        reportedImageAfter = getIndividualReportedImage(potholeID, reportID, imageID)<br/>    <br/>&gt;       assert reportedImageBefore != reportedImageAfter and &quot;Pothole image successfully deleted!&quot; in res[0][&quot;message&quot;]<br/><span class="error">E       AssertionError: assert (({&#x27;error&#x27;: &#x27;Pothole image not found!&#x27;}, 404) != ({&#x27;error&#x27;: &#x27;Pothole image not found!&#x27;}, 404))</span><br/><br/>App\tests\test_application.py:264: AssertionError@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/> -----------------------------Captured stdout setup------------------------------ <br/>https://www.howtogeek.com/wp-content/uploads/2018/08/Header.png
https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg
https://images.unsplash.com/photo-1541963463532-d68292c34b19?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mnx8fGVufDB8fHx8&amp;w=1000&amp;q=80
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">App/tests/test_application.py::testDeleteIndividualReportAsNonOwner</td>
          <td class="col-duration">0.03</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">simulated_db = &lt;FlaskClient &lt;Flask &#x27;App.main&#x27;&gt;&gt;<br/><br/>    def testDeleteIndividualReportAsNonOwner(simulated_db):<br/>        user2 = getOneRegisteredUser(&quot;tester2@yahoo.com&quot;)<br/>        potholeID = 1<br/>        reportID = 1<br/>    <br/>        rv = deleteUserPotholeReport(user2, potholeID, reportID)<br/>        oldRep = getIndividualPotholeReport(potholeID, reportID)<br/>    <br/>&gt;       assert &quot;Report does not exist! Unable to delete.&quot; in rv[0][&quot;error&quot;] and 404 == rv[1] and &quot;No report found.&quot; not in oldRep[0]<br/><span class="error">E       assert (&#x27;Report does not exist! Unable to delete.&#x27; in &#x27;Report does not exist! Unable to delete.&#x27; and 404 == 404</span><br/><span class="error">E         +404</span><br/><span class="error">E         -404 and &#x27;No report found.&#x27; not in &#x27;{&quot;error&quot;: &quot;...ort found.&quot;}&#x27;</span><br/><span class="error">E         &#x27;No report found.&#x27; is contained here:</span><br/><span class="error">E           {&quot;error&quot;: &quot;No report found.&quot;})</span><br/><br/>App\tests\test_application.py:400: AssertionError@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">App/tests/test_application.py::testDeleteLastReportDeletesPothole</td>
          <td class="col-duration">0.03</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">simulated_db = &lt;FlaskClient &lt;Flask &#x27;App.main&#x27;&gt;&gt;<br/><br/>    def testDeleteLastReportDeletesPothole(simulated_db):<br/>        user1 = getOneRegisteredUser(&quot;tester1@yahoo.com&quot;)<br/>        potholeID = 1<br/>        reportID = 1<br/>    <br/>        potholeBeforeDelete = displayIndividualPotholes(potholeID)[0]<br/>    <br/>        rv = deleteUserPotholeReport(user1, potholeID, reportID)<br/>        oldRep = getIndividualPotholeReport(potholeID, reportID)<br/>    <br/>        potholeAfterDelete = displayIndividualPotholes(potholeID)[0]<br/>    <br/>&gt;       assert &quot;Successfully deleted report.&quot; in rv[0][&quot;message&quot;] and 200 == rv[1] and &quot;No report found.&quot; in oldRep[0] and potholeBeforeDelete != potholeAfterDelete<br/><span class="error">E       KeyError: &#x27;message&#x27;</span><br/><br/>App\tests\test_application.py:425: KeyError@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">App/tests/test_application.py::testCalculateNetVotes</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">simulated_db = &lt;FlaskClient &lt;Flask &#x27;App.main&#x27;&gt;&gt;<br/><br/>    def testCalculateNetVotes(simulated_db):<br/>        potholeID = 1<br/>        reportID = 1<br/>    <br/>        user1 = getOneRegisteredUser(&quot;tester1@yahoo.com&quot;)<br/>        user2 = getOneRegisteredUser(&quot;tester2@yahoo.com&quot;)<br/>        user3 = getOneRegisteredUser(&quot;tester3@yahoo.com&quot;)<br/>        user4 = getOneRegisteredUser(&quot;tester4@yahoo.com&quot;)<br/>        user5 = getOneRegisteredUser(&quot;tester5@yahoo.com&quot;)<br/>    <br/>        voteOnPothole(user1, potholeID, reportID, {&quot;upvote&quot; : False})<br/>        voteOnPothole(user2, potholeID, reportID, {&quot;upvote&quot; : False})<br/>        voteOnPothole(user3, potholeID, reportID, {&quot;upvote&quot; : True})<br/>        voteOnPothole(user4, potholeID, reportID, {&quot;upvote&quot; : False})<br/>        voteOnPothole(user5, potholeID, reportID, {&quot;upvote&quot; : True})<br/>    <br/>        netVotes = calculateNetVotes(reportID)<br/>    <br/>&gt;       assert netVotes == -1<br/><span class="error">E       assert 0 == -1</span><br/><span class="error">E         +0</span><br/><span class="error">E         --1</span><br/><br/>App\tests\test_application.py:447: AssertionError@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">App/tests/test_application.py::testVoteOnPothole</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">simulated_db = &lt;FlaskClient &lt;Flask &#x27;App.main&#x27;&gt;&gt;<br/><br/>    def testVoteOnPothole(simulated_db):<br/>        user1 = getOneRegisteredUser(&quot;tester1@yahoo.com&quot;)<br/>        potholeID = 1<br/>        reportID = 1<br/>    <br/>        votesBefore = calculateNetVotes(reportID)<br/>        voteOnPothole(user1, potholeID, reportID, {&quot;upvote&quot; : True})<br/>        votesAfter = calculateNetVotes(reportID)<br/>    <br/>&gt;       assert votesBefore != votesAfter<br/><span class="error">E       assert 0 != 0</span><br/><br/>App\tests\test_application.py:484: AssertionError@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">App/tests/test_application.py::testChangeVoteOnPothole</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">simulated_db = &lt;FlaskClient &lt;Flask &#x27;App.main&#x27;&gt;&gt;<br/><br/>    def testChangeVoteOnPothole(simulated_db):<br/>        user1 = getOneRegisteredUser(&quot;tester1@yahoo.com&quot;)<br/>        potholeID = 1<br/>        reportID = 1<br/>    <br/>        votesBefore = calculateNetVotes(reportID)<br/>        voteOnPothole(user1, potholeID, reportID, {&quot;upvote&quot; : True})<br/>        votesMidway = calculateNetVotes(reportID)<br/>        voteOnPothole(user1, potholeID, reportID, {&quot;upvote&quot; : False})<br/>        votesAfter = calculateNetVotes(reportID)<br/>    <br/>&gt;       assert votesBefore != votesAfter != votesMidway<br/><span class="error">E       assert 0 != 0</span><br/><br/>App\tests\test_application.py:511: AssertionError@pytest.fixture<br/>    def simulated_db():<br/>        app = create_app({&#x27;TESTING&#x27;: True, &#x27;SQLALCHEMY_DATABASE_URI&#x27;: &#x27;sqlite:///test.db&#x27;})<br/>        init_db(app)<br/>        createSimulatedData()<br/>        yield app.test_client()<br/>&gt;       os.unlink(os.getcwd()+&#x27;/App/test.db&#x27;)<br/><span class="error">E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &#x27;C:\\Users\\jbald\\Desktop\\NULLIFY-finalProject/App/test.db&#x27;</span><br/><br/>App\tests\test_application.py:40: PermissionError<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">App/tests/test_application.py::testIdentifyUserNotLoggedIn</td>
          <td class="col-duration">0.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="empty log">No log output captured.</div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">App/tests/test_application.py::testRegisterInvalidData</td>
          <td class="col-duration">0.01</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="empty log">No log output captured.</div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">App/tests/test_application.py::testRegisterExistingUser</td>
          <td class="col-duration">0.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="empty log">No log output captured.</div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">App/tests/test_application.py::testDuplicateReportSameUser</td>
          <td class="col-duration">0.87</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> -----------------------------Captured stdout setup------------------------------ <br/>https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg
https://images.unsplash.com/photo-1541963463532-d68292c34b19?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mnx8fGVufDB8fHx8&amp;w=1000&amp;q=80
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">App/tests/test_application.py::testRoute</td>
          <td class="col-duration">0.00</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="empty log">No log output captured.</div></td></tr></tbody></table></body></html>